name: Auto Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  run-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install deps
        run: npm install || true

      - name: Start app
        run: npm start
